### ISSUE TITLE
Skeleton done

### ISSUE THREAD

**Issue by nstrayer** [nstrayer/activity_detection_post#1]
Currently, the skeleton loads in the data with a couple possible 'labels'. The main originally intended data is the activity being done in the recording, but we also could try and predict the individual being recorded. 

I put basic headers up for the next steps to fill in (also the wording will be cleared up for the first parts). 

@jjallaire @skeydan

**Comment by skeydan** [comment]
Hi Nick,

that's a great dataset & question I think! That should make for a very interesting case study for people to read!

I don't know if we told you already, we need to make the outputs static (to avoid overhead with later redeployments). Thanks!

**Comment by nstrayer** [comment]
Sigrid, 

When you say 'static' do you just mean that it's an RMD and not a shiny app?

**Comment by jjallaire** [comment]
I am hoping to covert the TF for R blog over to Radix soon so if you just author the post within this Git repo and use radix::radix_article (docs here: https://radixpub.github.io/radix-r/) we should be fine.

Static outputs refers to hard coding the text and graphics output, which we used to need to do for our blogdown based TF for R blog. With Radix we'll be able to import your HTML directly (so you author however you want, use knitr or a custom caching scheme, etc.).

**Comment by skeydan** [comment]
JJ was faster

**Comment by nstrayer** [comment]
Ah, I see -- got it! 

I was checking out the radix site today and it is looking super slick.
