### ISSUE TITLE
Draft done

### ISSUE THREAD

**Issue by nstrayer** [nstrayer/activity_detection_post#2]
Hi @jjallaire @skeydan,

I have finished a preliminary draft of the activity detection post. 

My preliminary thoughts are that it may be a bit too long. I included some code for manipulating results/ visualizations that maybe could be cut and included in an appendix or linked repo?

I have hosted the Rmd through github pages so you can see it by going to [nickstrayer.me/activity_detection_post](http://nickstrayer.me/activity_detection_post/). 

Have a fantastic weekend!

**Comment by nstrayer** [comment]
Oops, had forgotten to push my latest commits actually containing the completed draft. Did just now and they should propagate to the ghpages site shortly.

**Comment by skeydan** [comment]
Hi Nick,

great, we'll take a look! Have a fantastic weekend you too!

**Comment by jjallaire** [comment]
Excellent! On first blush it doesn't seem too long to me. I will take a closer look on Monday and provide any feedback I have via inline comments / gh issues.
